[package]
name = "packages.tricti.dev"
version = "0.0.0"
license = "GPL-3.0-or-later"
description = "This is the backend of the TriCTI Package Manager"

[dependencies]
tricti-http = { version = "0.0.0", features = ["routing"] }
tricti-git2 = 0.0.0